"""Per-case verdicts of every holdout, as one Markdown file: python verdict_table.py  ->  VERDICTS.md

Reads results/holdout_v*/summary.json (written by entail's eval/block_fp8_guarantee/aggregate.py) and lists, per
version, each case's verdict in every mode, the off baseline's worst ratio to the tolerance for defect and integrity
cases, and the mode's state. Nothing is judged here: the verdicts are the aggregator's.
"""
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
EVAL = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "entail", "eval", "block_fp8_guarantee")
MODES = ("offA", "load", "guarantee", "structure")
SHORT = {"normal_delivered": "normal", "repaired_delivered": "repaired", "blocked": "blocked",
         "wrong_escaped": "**escaped**", "refused_after_use": "**refused after use**", "unknown": "unknown",
         "error": "error", "wrong_refusal": "**wrong refusal**", "changed_without_need": "**changed**",
         "delivered": "**delivered**", "other": "other", None: "-"}


def version(path):
    m = re.search(r"holdout_v(\d+)", path)
    return int(m.group(1)) if m else 0


def main():
    out = ["# Per-case verdicts of the holdouts (M19 L5.4)", "",
           "Generated by `verdict_table.py` from `results/holdout_v*/summary.json` (entail "
           "`eval/block_fp8_guarantee/aggregate.py`). A verdict is what the next operation read, judged by the "
           "independent oracle. v1 and v2 ran the guarantee profile with check `output` (v1) and `static` (v2) under "
           "`ENTAIL=guarantee`; from v3 the structural check is the separate experiment `ENTAIL=structure`, reported "
           "under its own column. The holdouts are not blind (no separate evaluator); their seeds come from the hash "
           "of each version's freeze manifest.", ""]
    for path in sorted(glob.glob(os.path.join(HERE, "results", "holdout_v*", "summary.json")), key=version):
        with open(path, encoding="utf-8") as f:
            s = json.load(f)
        v = version(path)
        modes = [m for m in MODES if m in s["modes"] or any(m in j["modes"] and j["modes"][m].get("present")
                                                             for j in s["per_case"])]
        label = {"guarantee": "guarantee (static)" if v == 2 else "guarantee"}
        out += [f"## holdout v{v}", ""]
        states = ", ".join(f"{label.get(m, m)}: **{s['modes'][m]['state']}**" for m in modes if m in s["modes"])
        complete = s.get("complete")
        if complete is None:                 # summaries written before v4: read again (in memory) by the v4 aggregator
            try:
                import sys

                sys.path.insert(0, EVAL)
                import aggregate

                again = aggregate.summarize(os.path.dirname(path))
                unfinished = sum(len(x) for x in again["unfinished_runs"].values())
                complete = f"{again['complete']} (read again by the v4 aggregator; unfinished runs: {unfinished})"
            except Exception as e:  # noqa: BLE001
                complete = f"not recorded (before v4; not read again: {type(e).__name__})"
        out += [f"States: {states}. Complete: {complete}.", ""]
        out += ["| case | group | off worst ratio | " + " | ".join(label.get(m, m) for m in modes) + " |",
                "|---|---|---:|" + "---|" * len(modes)]
        for j in s["per_case"]:
            ob = j.get("off_baseline") or {}
            ratio = f"{ob['worst_ratio']:.1f}" if ob.get("worst_ratio") else ""
            cells = []
            for m in modes:
                mm = j["modes"].get(m, {})
                if not mm.get("present"):
                    cells.append("missing")
                    continue
                cell = SHORT.get(mm.get("verdict"), str(mm.get("verdict")))
                if mm.get("refusal_kinds") and j["group"] in ("admission", "integrity"):
                    kinds = sorted({k for k in mm["refusal_kinds"] if k})
                    if kinds:
                        cell += f" ({', '.join(kinds)})"
                if j["group"] == "normal" and mm.get("bitwise_as_offA") is True and m != "offA":
                    cell += ", bitwise = off A"
                cells.append(cell)
            out.append(f"| {j['id']} | {j['group']} | {ratio} | " + " | ".join(cells) + " |")
        out.append("")
    with open(os.path.join(HERE, "VERDICTS.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote VERDICTS.md:", len(out), "lines")


if __name__ == "__main__":
    main()
