"""M10 E1: testbed/results/m10/E1_SUMMARY.md from the files the E1 scripts wrote. Values are read from those files only.
  L       results/m10/e1_llm/models.json (m10_e1_fetch.py), static.json (m10_e1_static.py),
          rope_off.json / rope_on.json (m10_e1_rope.py), coverage_keys.json (below)
  I       results/m10/e1_images/checkpoints.json (m10_e1_images.py)
Run: python testbed/m10_e1_summarize.py
"""
import json
import os
import re
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(HERE, "results", "m10")
L1 = os.path.join(R, "e1_llm")


def j(*p):
    path = os.path.join(*p)
    return json.load(open(path, encoding="utf-8")) if os.path.exists(path) else None


def pct(a, b):
    return f"{a}/{b} ({100 * a / b:.0f}%)" if b else f"{a}/0"


def fields(text):
    m = re.search(r"ModelProps\(([^)]*)\)", text)
    return dict(kv.split("=", 1) for kv in (m.group(1).split(", ") if m else []) if "=" in kv)


def main():
    L = ["# M10 E1: exposure in public model files (no GPU)", "",
         "Generated by `testbed/m10_e1_summarize.py` from the files named in each section. Definitions: "
         "`testbed/M10_PROTOCOL.md` 1 and 6.", ""]
    models = j(L1, "models.json")
    rows = models["models"]
    dl = {r["id"]: r["downloads_30d"] or 0 for r in rows}
    gated = sum(1 for r in rows if r["gated"])
    cfg = [r for r in rows if (r["fetch"]["files"].get("config.json") or {}).get("status") == 200]
    L += ["## Population L", "",
          f"Hugging Face `pipeline_tag=text-generation`, the {len(rows)} most downloaded (30 days), queried "
          f"{models['when']}. Gated (not read, no token): {gated}. No `config.json` (GGUF-only and other formats): "
          f"{len(rows) - gated - len(cfg)}. Config files read: {len(cfg)}. Weights were not downloaded.", ""]

    # L1
    off, on = j(L1, "rope_off.json"), j(L1, "rope_on.json")
    on_by = {r["id"]: r for r in on["rows"]}
    L += ["## L1: the RoPE override at launch (vLLM 0.30's own ModelConfig; code, not an end-to-end run)", "",
          "Passing `rope_scaling` at launch (`--hf-overrides`) - the model's own value restated, or the YaRN value "
          "model cards give for long context - and comparing the RoPE base vLLM would use with the untouched one.", "",
          "Calibration (the local models; Llama-3.2-3B-Instruct was measured end to end: GSM8K 379 -> 273/500):", "",
          "| model | entail off | base untouched -> with the override | entail on |", "|---|---|---|---|"]
    for r in off["rows"]:
        if r["id"].startswith("local/"):
            o = on_by[r["id"]]
            L.append(f"| {r['id'][6:]} | {r['result']} | {r.get('base_untouched')} -> {r.get('base_override')} | "
                     f"{o['result']} {o.get('base_override') or ''} |")
    pop = [r for r in off["rows"] if not r["id"].startswith("local/")]
    c = Counter(r["result"] for r in pop)
    applies = [r for r in pop if r["result"] in ("exposed", "not exposed", "override fails loudly at config build",
                                                 "structure changed")]
    exposed = [r for r in pop if r["result"] == "exposed"]
    loud = [r for r in pop if r["result"] == "override fails loudly at config build"]
    fixed_on = [r for r in applies if on_by[r["id"]]["result"] == "not exposed"]
    w_all, w_exp = sum(dl[r["id"]] for r in applies), sum(dl[r["id"]] for r in exposed)
    L += ["", f"Population ({len(pop)} config folders): " + ", ".join(f"{k} {v}" for k, v in c.most_common()), "",
          f"- The override applies to {len(applies)} models (registered in vLLM 0.30, RoPE in its model files, the "
          f"config builds).",
          f"- **Silently exposed: {pct(len(exposed), len(applies))}**; by downloads, {100 * w_exp / w_all:.0f}% of the "
          f"downloads of those {len(applies)} models.",
          f"- Fails loudly at config build: {len(loud)}. Structure changed (per-layer RoPE flattened): "
          f"{c.get('structure changed', 0)}.",
          f"- **entail on: {pct(len(fixed_on), len(applies))} keep the untouched base** (including the loud ones).",
          "", "Override kinds among the exposed: " + ", ".join(f"{k} {v}" for k, v in
                                                          Counter(r["override_kind"] for r in exposed).items()), "",
          "| rank | model | downloads (30 d) | base untouched -> override | override | entail on |",
          "|---|---|---|---|---|---|"]
    for r in sorted(exposed, key=lambda r: r["rank"]):
        L.append(f"| {r['rank']} | {r['id']} | {dl[r['id']]:,} | {r['base_untouched']['-'] if '-' in r['base_untouched'] else r['base_untouched']} -> "
                 f"{r['base_override']['-'] if '-' in r['base_override'] else r['base_override']} | "
                 f"{r['override_kind']} | {on_by[r['id']]['result']} |")

    # L1 end to end
    e2e = os.path.join(L1, "e2e")
    runs = [j(e2e, f) for f in sorted(os.listdir(e2e)) if f.endswith(".json")] if os.path.isdir(e2e) else []
    if runs:
        L += ["", "End to end on vLLM 0.30 (GSM8K, first problems, greedy; `testbed/m10_e1_rope_e2e.py`):", "",
              "| run | model | entail | correct | RoPE parameters the engine holds |", "|---|---|---|---|---|"]
        for r in runs:
            L.append(f"| {r['name']} | {r['model']} | {r['entail']} | {r['correct']}/{r['n']} | "
                     f"{r['rope_parameters_in_engine']} |")
        by = {r["name"]: r for r in runs}
        for tag in sorted({n.rsplit('_', 2)[0] for n in by if n.endswith("_override_off")}):
            off, on = by.get(f"{tag}_override_off"), by.get(f"{tag}_override_on")
            if off and on:
                from math import comb
                a, b = off["per_problem"], on["per_problem"]
                n10, n01 = sum(y and not x for x, y in zip(a, b)), sum(x and not y for x, y in zip(a, b))
                k, n = min(n10, n01), n10 + n01
                p = min(1.0, 2 * sum(comb(n, i) for i in range(k + 1)) / 2 ** n) if n else 1.0
                L.append(f"\n{tag}: override with entail on vs off: {on['correct']} vs {off['correct']} correct; "
                         f"only on right {n10}, only off right {n01}; McNemar exact p = {p:.4f}")

    # L2
    st = j(L1, "static.json")
    L += ["", "## L2: declared attention properties a backend drops (entail 1.0 static check, every backend in the "
          "capability table)", "", "| engine | models with a backend that drops a declared property | properties | "
          "entail's verdicts on those backends |", "|---|---|---|---|"]
    for eng in ("transformers", "vllm", "sglang"):
        ms, props, verdicts = set(), Counter(), Counter()
        for r in st["rows"]:
            for cons, b in r["engines"][eng]["backends"].items():
                if b["verdict"] in ("resolved", "broken", "refused"):
                    ms.add(r["id"])
                    verdicts[b["verdict"]] += 1
                    d, u = fields(b["line"].split(" uses ")[0]), fields(b["line"].split(" uses ")[1]) \
                        if " uses " in b["line"] else {}
                    for k in d:
                        if d.get(k) not in (None, "None") and u.get(k) in (None, "None"):
                            props[k] += 1
        L.append(f"| {eng} | {len(ms)} of {len(st['rows'])} | {dict(props)} | {dict(verdicts)} |")
    L += ["", "A backend listed here drops the property if it is chosen; which backend each engine picks by default "
          "is measured in E2, not here."]

    # L3
    ck = j(L1, "coverage_keys.json")
    L += ["", "## L3: config keys the engine's config class does not take (entail 1.0 reports them as broken)", "",
          f"{len(ck['per_model'])} of {len(st['rows'])} folders; {len(ck['keys'])} distinct keys. Most frequent:", ""]
    L += [f"- `{k}`: {n}" for k, n in ck["keys"][:20]]
    L += ["", "Whether a key is lost, or carried on the config object and read by the engine (a false alarm), is not "
          "decided here: E2 counts the reports on real runs."]

    # L4
    L += ["", "## L4: what the folders declare", ""]
    have = Counter()
    for r in st["rows"]:
        dec = r.get("declared") or {}
        for name, facts in dec.items():
            if facts:
                have[name] += 1
        mp = " ".join(f["value"] for f in dec.get("ModelProps", []))
        if re.search(r"softcap=[0-9]", mp):
            have["ModelProps.softcap"] += 1
        if re.search(r"sliding_window=[0-9]", mp):
            have["ModelProps.sliding_window"] += 1
    L += [f"- {k}: {v} of {len(st['rows'])}" for k, v in sorted(have.items())]

    # I
    ck_img = j(R, "e1_images", "checkpoints.json")
    L += ["", "## Population I and its measure: single-file image checkpoints (Civitai)", ""]
    if not ck_img:
        L.append("(checkpoints.json missing)")
    else:
        for period in ("AllTime", "Year"):
            rs = [r for r in ck_img["rows"] if r["period"] == period]
            ok = [r for r in rs if r.get("read") == "ok"]
            unet = [r for r in ok if any(s in str(r.get("base_model")) for s in
                                         ("SD 1.5", "SDXL", "Pony", "Illustrious", "NoobAI", "SD 2"))]
            key_v = [r for r in unet if r.get("key_v_pred")]
            meta_v = [r for r in unet if not r.get("key_v_pred") and any(x["kind"] == "v" for x in r["entail_reads"])]
            vmodels = [r for r in unet if r.get("key_v_pred") or any(x["kind"] == "v" for x in r["entail_reads"])
                       or r.get("named_v")]
            nothing = [r for r in unet if not r["entail_reads"]]
            v_no_key = [r for r in vmodels if not r.get("key_v_pred")]
            v_nothing = [r for r in vmodels if not r["entail_reads"]]
            L += [f"### {period} (top {len(rs)}, queried {ck_img['when']})", "",
                  f"- Header read: {len(ok)}; not read: {len(rs) - len(ok)} "
                  f"({dict(Counter(str(r.get('read'))[:40] for r in rs if r.get('read') != 'ok'))})",
                  f"- UNet (SD 1.5 / SD 2 / SDXL family) checkpoints read: {len(unet)}; other bases: "
                  f"{dict(Counter(r.get('base_model') for r in ok if r not in unet))}",
                  f"- Declare no prediction type at all (tools guess, eps by default): {pct(len(nothing), len(unet))}",
                  f"- v-prediction models (declared, or named so; a lower bound): {len(vmodels)}",
                  f"  - with the `v_pred` key ComfyUI reads: {len(key_v)}; declared only in metadata: {len(meta_v)}; "
                  f"declared nowhere in the file (named only): {len(v_nothing)}",
                  f"  - exposed on ComfyUI 0.34.1 (no `v_pred` key): {len(v_no_key)}; on diffusers 0.40 single-file "
                  f"(reads neither): {len(vmodels)}",
                  f"  - entail: resolves {len(vmodels) - len(v_nothing)} from the file's own declaration; reports "
                  f"{len(v_nothing)} as unknown (a manifest is needed)", ""]
    out = "\n".join(L) + "\n"
    with open(os.path.join(R, "E1_SUMMARY.md"), "w", encoding="utf-8") as f:
        f.write(out)
    print(out)


if __name__ == "__main__":
    main()
