"""Summarise the M4.2 real-engine runs (testbed/m42_vllm_layout.sh) from their result files only.

For each run: exit code (from the log: a RoleError or a TEXT line), the output text, the planted defect's count, the
decisions at the signed repack boundary (from the ENTAIL_RECORD file), and entail's own time there. Writes
testbed/results/m42/SUMMARY.md and SUMMARY.json. Usage: python testbed/m42_summarize.py [results dir]
"""
import collections
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = [("healthy_none", "none", "-", "load", "refuse"), ("healthy_fp8", "fp8", "-", "load", "refuse"),
        ("roll_on", "none", "roll_output", "load", "refuse"), ("roll_off", "none", "roll_output", "off", "refuse"),
        ("transpose_on", "none", "transpose_all", "load", "refuse"),
        ("strided_on", "none", "strided_weights", "load", "refuse"),
        ("strided_usedata", "none", "strided_weights", "load", "use_data")]
BOUNDARY = "load:vllm.quant_method.process_weights_after_loading"


def one(folder, tag):
    log = open(os.path.join(folder, tag + ".log"), encoding="utf-8", errors="replace").read()
    text = next((l[len("TEXT: "):] for l in log.splitlines() if l.startswith("TEXT: ")), None)
    seed = re.search(r"\[entail-seed\] \w+: (\d+) linear weights seen, (\d+) square, (\d+) changed", log)
    stopped = "RoleError" in log
    decisions, weights, timing = collections.Counter(), collections.Counter(), []
    notes = []
    path = os.path.join(folder, tag + ".jsonl")
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            d = json.loads(line)
            if "timing" in d:
                if d["timing"] == BOUNDARY:
                    timing.append(d["ms"])
            elif d.get("boundary") == BOUNDARY:
                key = f"{d['name']} {d['verdict']}"
                decisions[key] += 1   # a grouped decision names how many weights it covers; a per-weight one, one
                m = re.match(r"(\d+) weight\(s\)", d.get("note") or "")
                weights[key] += int(m.group(1)) if m else 1
                if d["verdict"] != "pass":
                    notes.append(f"{d['name']} {d['verdict']}: {(d.get('note') or '')[:160]}")
    return {"text": text, "stopped": stopped, "seed_changed": int(seed.group(3)) if seed else 0,
            "decisions": dict(sorted(decisions.items())), "weights": dict(sorted(weights.items())),
            "ms_before_and_after": timing, "notes": notes}


def main():
    folder = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "results", "m42")
    rows = {tag: {"quant": q, "seed": s, "entail": e, "false_declaration": f, **one(folder, tag)}
            for tag, q, s, e, f in RUNS if os.path.exists(os.path.join(folder, tag + ".log"))}
    with open(os.path.join(folder, "SUMMARY.json"), "w", encoding="utf-8") as fh:
        json.dump(rows, fh, ensure_ascii=False, indent=1)
    out = ["# M4.2: the signed vLLM repack boundary on a real engine", "",
           "Generated by `testbed/m42_summarize.py` from the logs and ENTAIL_RECORD files in this folder.",
           "Qwen3-4B, vLLM 0.30.0, RTX 4070 Ti. Planted defects: `entail/entail/adapters/vllm_seed.py`.", "",
           "| run | quant | planted | ENTAIL | false declaration | weights changed | server | text | at the boundary: "
           "weights (decisions) | entail ms (before, after) |", "|---|---|---|---|---|---|---|---|---|---|"]
    for tag, r in rows.items():
        server = "refused to start" if r["stopped"] else ("answered" if r["text"] is not None else "?")
        dec = ", ".join(f"{k} {r['weights'][k]} ({v})" for k, v in r["decisions"].items()) or "-"
        ms = ", ".join(f"{m:.1f}" for m in r["ms_before_and_after"]) or "-"
        out.append(f"| {tag} | {r['quant']} | {r['seed']} | {r['entail']} | {r['false_declaration']} | "
                   f"{r['seed_changed']} | {server} | {r['text'] or '-'} | {dec} | {ms} |")
    out += ["", "Decisions that were not a pass (note as recorded, cut at 160 characters):", ""]
    for tag, r in rows.items():
        for n in r["notes"]:
            out.append(f"- {tag}: {n}")
    with open(os.path.join(folder, "SUMMARY.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
