"""Summarise the M5.1 measurements from their result files only (testbed/results/m51/).

  transformers.json          testbed/m51_transformers.py: Qwen3-4B, dynamic and static cache, a token lost
  <engine>_<tag>.json/.log   testbed/m51_engines.sh: vLLM and SGLang, off / on / a planted defect
  <engine>_<tag>.jsonl       ENTAIL_RECORD: decisions, and what each container boundary checked (the last summary
                             line per process and boundary counts; engines check in child processes)
Writes SUMMARY.md and SUMMARY.json next to them. Usage: python testbed/m51_summarize.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DIR = os.path.join(HERE, "results", "m51")
RUNS = [("vllm", "off", "off"), ("vllm", "on", "load"), ("vllm", "seeded", "load"), ("sglang", "off", "off"),
        ("sglang", "on", "load"), ("sglang", "seeded", "load")]


def engine_run(engine, tag, mode):
    base = os.path.join(DIR, f"{engine}_{tag}")
    if not os.path.exists(base + ".log"):
        return None
    if os.path.exists(base + ".json"):
        res = json.load(open(base + ".json", encoding="utf-8"))
    else:   # SGLang kills its whole process group when the scheduler stops: the runner never wrote its result
        res = {"entail": mode, "texts": None, "error": "no result file: the engine's process group was killed after "
                                                        "its scheduler stopped (see the log)"}
    containers, refusals = {}, []
    if os.path.exists(base + ".jsonl"):
        for line in open(base + ".jsonl", encoding="utf-8"):
            d = json.loads(line)
            counted = d.get("boundaries", d.get("container"))   # "container" until M5.2 moved it to tally.py
            if counted is not None:
                for boundary, s in counted.items():
                    containers[(d["pid"], boundary)] = s   # the last summary of each process wins
            elif d.get("verdict") not in (None, "pass"):
                refusals.append(f"{d['verdict']} at {d['boundary']}: {d['rule']}; {(d.get('note') or '')[:200]}")
    log = open(base + ".log", encoding="utf-8", errors="replace").read()
    res["planted"] = [l.split("[entail-seed]", 1)[1].strip() for l in log.splitlines() if "[entail-seed]" in l][:2]
    res["container"] = {f"{b} (pid {p})": s for (p, b), s in sorted(containers.items())}
    res["not_passed"] = refusals
    return res


def main():
    out = {"transformers": json.load(open(os.path.join(DIR, "transformers.json"), encoding="utf-8"))
           if os.path.exists(os.path.join(DIR, "transformers.json")) else None,
           "engines": {f"{e}_{t}": engine_run(e, t, m) for e, t, m in RUNS}}
    with open(os.path.join(DIR, "SUMMARY.json"), "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    lines = ["# M5.1: the KV container contract after its rules moved to the core", "",
             "Generated by `testbed/m51_summarize.py` from the files in this folder. Qwen3-4B on an RTX 4070 Ti.", ""]
    t = out["transformers"]
    if t:
        lines += [f"## transformers {t['transformers']} (torch {t['torch']}), {t['new_tokens']} greedy tokens", "",
                  "| cache | pairs | median off / on / off control (s) | on / off | control / off | same output | "
                  "checked at update | deferred to the device | after the request | refused |",
                  "|---|---|---|---|---|---|---|---|---|---|"]
        for key in ("dynamic", "static"):
            r = t[key]
            u, a = r["update_boundary"], r["after_request"]
            lines.append(f"| {key} | {r['pairs']} | {r['median']['off']} / {r['median']['load']} / "
                         f"{r['median']['off_control']} | {r['multiplier']} | {r['control_multiplier']} | "
                         f"{r['same_output']} | {u['checks']} (passes {u['passed']}) | {u['deferred']} | "
                         f"{a['checks']} (passes {a['passed']}) | {u['refused'] + a['refused']} |")
        lines += ["", f"A token lost from every layer between two steps: contract off, the decode went on "
                      f"({t['seeded_off']['tokens']}); on, refused: `{t['seeded_on'].get('error', '')[:300]}`", ""]
    lines += ["## vLLM and SGLang", "",
              "Checked: the last summary each engine process wrote. vLLM's EngineCore writes one at exit; SGLang's "
              "scheduler is not let to exit normally, so its last line is the last power of two it reached.", "",
              "| run | ENTAIL | planted | texts or error | checked (per process) | not a pass |",
              "|---|---|---|---|---|---|"]
    for key, r in out["engines"].items():
        if r is None:
            continue
        texts = "; ".join(r["texts"]) if r.get("texts") else (r.get("error") or "-")
        checked = "; ".join(f"{b}: checks {s['checks']}, skipped {s['skipped']}, refused {s['refused']}"
                            for b, s in r["container"].items()) or "-"
        lines.append(f"| {key} | {r['entail']} | {'; '.join(r['planted']) or '-'} | {texts[:150]} | {checked} | "
                     f"{'<br>'.join(r['not_passed'])[:400] or '-'} |")
    with open(os.path.join(DIR, "SUMMARY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
