"""Summarise the M5.3 measurements from their result files only (testbed/results/m53/).

  <server>_<tag>.json/.log   testbed/m53_serve.py: vLLM 0.30.0 serving Qwen3-4B, entail off / on / refuse policy
  <server>_<tag>.jsonl       ENTAIL_RECORD: decisions, and what each boundary counted (the last summary per process)
  tool_llama3_off.*          the first tool run, with the llama3_json parser (kept: it fails loudly on Qwen3)
  overhead.json              testbed/m53_overhead.py: entail's part of one request against its rendering
Writes SUMMARY.md next to them. Usage: python testbed/m53_summarize.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DIR = os.path.join(HERE, "results", "m53")
RUNS = [("healthy", "off"), ("healthy", "on"), ("keep", "off"), ("keep", "on"), ("tool_llama3", "off"),
        ("tool", "off"), ("tool", "on"), ("tool", "refuse")]


def shown(r):
    if r["status"] != 200:
        return f"{r['status']}: {r.get('error', '')[:150]}"
    parts = [repr(r.get("content", "")[:40])]
    if r.get("tool_calls"):
        parts.append("tool_calls " + ", ".join(f"{c['name']}({c['arguments']})" for c in r["tool_calls"]))
    if r.get("reasoning_chars"):
        parts.append(f"reasoning {r['reasoning_chars']} chars")
    return "200: " + "; ".join(parts)


def main():
    lines = ["# M5.3: the request boundary on a vLLM server", "",
             "Generated by `testbed/m53_summarize.py` from the files in this folder. vLLM 0.30.0 serving Qwen3-4B "
             "(`--enforce-eager`, the qwen3 reasoning parser) on an RTX 4070 Ti; entail installed by the sitecustomize "
             "shim, the declaration a pinned manifest in `manifests/<server>/` (ENTAIL_MANIFESTS).", ""]
    runs = {}
    for server, tag in RUNS:
        p = os.path.join(DIR, f"{server}_{tag}.json")
        if os.path.exists(p):
            runs[(server, tag)] = json.load(open(p, encoding="utf-8"))
    for server in ("healthy", "keep", "tool_llama3", "tool"):
        tags = [t for s, t in RUNS if s == server and (s, t) in runs]
        if not tags:
            continue
        first = runs[(server, tags[0])]
        lines += [f"## {server}", "", f"Server arguments: `{' '.join(first['args'])}`. Declared: `{first['declared']}`.",
                  ""]
        names = list(first.get("requests", {}))
        if names:
            lines += ["| request | what | " + " | ".join(tags) + " |", "|---|---|" + "---|" * len(tags)]
            for n in names:
                what = first["requests"][n]["what"]
                cells = [shown(runs[(server, t)]["requests"][n]) if runs[(server, t)].get("requests") else
                         "server did not start" for t in tags]
                lines.append(f"| {n} | {what} | " + " | ".join(c.replace("|", "&#124;").replace("\n", " ") for c in cells)
                             + " |")
            lines.append("")
        for t in tags:
            r = runs[(server, t)]
            if not r.get("started"):
                lines.append(f"- `{t}`: the server did not start (exit {r.get('exit')}): "
                             f"{(r.get('log_entail') or [''])[0][:300]}")
            for d in r.get("decisions", []):
                lines.append(f"- `{t}` decision: {d['verdict']} at {d['boundary']}: {d['rule']}"
                             f"{'; ' + d['resolution'] if d.get('resolution') else ''}")
            counted = {k.split(' ', 1)[1]: v for k, v in r.get("summaries", {}).items()}
            for b, s in sorted(counted.items()):
                lines.append(f"- `{t}` counted at {b}: checks {s.get('checks', 0)}, refused {s.get('refused', 0)}, "
                             f"skipped {s.get('skipped', 0)}, passes {s.get('passed', {})}")
        lines.append("")
    p = os.path.join(DIR, "overhead.json")
    if os.path.exists(p):
        o = json.load(open(p, encoding="utf-8"))
        lines += ["## Cost per request", "",
                  f"`overhead.json` (testbed/m53_overhead.py): vLLM {o['vllm']}'s own functions, {o['model']}'s "
                  f"tokenizer and template, no GPU; {o['n']} calls per side, alternating order, medians. entail's part: "
                  "the policy read once, the fields check, and everything decided before rendering. The rendering: "
                  "Hugging Face apply_chat_template with tokenizing, which vLLM runs for the request next.", "",
                  "| request | entail (µs) | rendering (µs) | entail / rendering |", "|---|---|---|---|"]
        for n, s in o["shapes"].items():
            lines.append(f"| {n} | {s['entail_us']} | {s['render_us']} | {s['ratio']} |")
        lines.append("")
    out = os.path.join(DIR, "SUMMARY.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
