"""Summarise the M5.4 measurements from their result files only (testbed/results/m54/).

  <server>_<tag>.json/.log/.jsonl   testbed/m54_serve.py: the M5.3 servers under the policy that reports and goes on
  vllm_seeded_report.*              the M5.1 vLLM run, block table planted one block short, under the same policy
  overhead.json                     testbed/m53_overhead.py with TESTBED_OUT: the cost per request
Writes SUMMARY.md next to them. Usage: python testbed/m54_summarize.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# M9.1: TESTBED_RESULTS moves the results (a re-run on the final code keeps each milestone's own results)
RESULTS = os.path.abspath(os.environ.get("TESTBED_RESULTS") or os.path.join(HERE, "results"))
DIR = os.path.join(RESULTS, "m54")
RUNS = [("healthy", "on"), ("healthy", "note"), ("healthy", "strict"), ("keep", "on"), ("tool", "on"),
        ("tool", "observe"), ("tool", "observe_strict")]


def cell(r):
    if r["status"] != 200:
        return f"{r['status']}"
    parts = ["200"]
    if r.get("tool_calls"):
        parts.append("tool call " + r["tool_calls"][0]["name"])
    elif r.get("content", "").lstrip().startswith("<tool_call>"):
        parts.append("tool call as text")
    if r.get("entail_field"):
        parts.append(f"entail field: {len(r['entail_field'])}")
    return ", ".join(parts)


def counted(res):
    out = {}
    for k, s in res.get("summaries", {}).items():
        b = k.split(" ", 1)[1]
        if s.get("broken") or s.get("refused"):
            out[b] = f"broken {s.get('broken', 0)}, refused {s.get('refused', 0)}, checks {s.get('checks', 0)}"
    return out


def main():
    lines = ["# M5.4: the policy that reports what it cannot repair and goes on", "",
             "Generated by `testbed/m54_summarize.py` from the files in this folder. vLLM 0.30.0 serving Qwen3-4B "
             "on an RTX 4070 Ti, the M5.3 requests and manifests (testbed/m53_serve.py). Tags: `on` the default policy; "
             "`note` with ENTAIL_RESPONSE_NOTE=1; `strict` with ENTAIL_ON_BROKEN=stop; `observe` with "
             "ENTAIL_POLICY=refuse (nothing repaired); `observe_strict` with both.", ""]
    for server in ("healthy", "keep", "tool"):
        tags = [t for s, t in RUNS if s == server and os.path.exists(os.path.join(DIR, f"{server}_{t}.json"))]
        if not tags:
            continue
        runs = {t: json.load(open(os.path.join(DIR, f"{server}_{t}.json"), encoding="utf-8")) for t in tags}
        first = runs[tags[0]]
        lines += [f"## {server}", "", f"Server arguments: `{' '.join(first['args'])}`. Declared: `{first['declared']}`.",
                  "", "| request | what | " + " | ".join(tags) + " |", "|---|---|" + "---|" * len(tags)]
        names = next((list(r["requests"]) for r in runs.values() if r.get("requests")), [])
        for n in names:
            what = next(r["requests"][n]["what"] for r in runs.values() if r.get("requests"))
            cells = [cell(runs[t]["requests"][n]) if runs[t].get("requests") else "server did not start"
                     for t in tags]
            lines.append(f"| {n} | {what} | " + " | ".join(cells) + " |")
        streamed = [(t, runs[t]["stream"]) for t in tags if runs[t].get("stream")]
        if streamed:
            lines.append("| stream (" + streamed[0][1]["request"] + ") | planted | " + " | ".join(
                f"{runs[t]['stream']['status']}, {runs[t]['stream']['data_lines']} data lines, "
                f"{len(runs[t]['stream']['comments'])} comment line(s)" if runs[t].get("stream") else "-"
                for t in tags) + " |")
        lines.append("")
        for t in tags:
            r = runs[t]
            kinds = {}
            for d in r.get("decisions", []):
                kinds[(d["boundary"], d["verdict"])] = kinds.get((d["boundary"], d["verdict"]), 0) + 1
            shown = "; ".join(f"{b} {v} x{n}" for (b, v), n in sorted(kinds.items())) or "none"
            lines.append(f"- `{t}`: recorded {shown}" + ("" if r.get("started") else
                                                         f"; the server did not start (exit {r.get('exit')})"))
            for b, c in sorted(counted(r).items()):
                lines.append(f"  - counted at {b}: {c}")
        lines.append("")
    kv = os.path.join(DIR, "vllm_seeded_report.json")
    if os.path.exists(kv):
        r = json.load(open(kv, encoding="utf-8"))
        off = os.path.join(RESULTS, "m51", "vllm_off.json")
        same = json.load(open(off, encoding="utf-8"))["texts"] == r["texts"] if os.path.exists(off) else None
        recorded, summary = 0, {}
        for line in open(kv.replace(".json", ".jsonl"), encoding="utf-8"):
            e = json.loads(line)
            if "boundaries" in e:
                summary.update({f"{b} (pid {e['pid']})": s for b, s in e["boundaries"].items()
                                if b.startswith("container:")})
            elif e.get("verdict") not in (None, "pass"):
                recorded += 1
        lines += ["## KV block table planted one block short (the M5.1 vLLM run, `ENTAIL_SEED=short_blocks`)", "",
                  f"- error: {r['error']}; the texts are the same as the M5.1 run with entail off: {same}",
                  f"- recorded: {recorded} decision(s); counted: " + "; ".join(
                      f"{b}: checks {s['checks']}, broken {s.get('broken', 0)}, refused {s['refused']}"
                      for b, s in summary.items()), ""]
    p = os.path.join(DIR, "overhead.json")
    if os.path.exists(p):
        o = json.load(open(p, encoding="utf-8"))
        lines += ["## Cost per request", "", "| request | entail (µs) | rendering (µs) | entail / rendering |",
                  "|---|---|---|---|"]
        lines += [f"| {n} | {s['entail_us']} | {s['render_us']} | {s['ratio']} |" for n, s in o["shapes"].items()]
        lines.append("")
    with open(os.path.join(DIR, "SUMMARY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.join(DIR, "SUMMARY.md"))


if __name__ == "__main__":
    main()
