"""M7.3: testbed/results/m73/SUMMARY.md from the files m73_locate.py and m73_tolerance.py wrote.

Run: python testbed/m73_summarize.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.abspath(os.environ.get("TESTBED_RESULTS") or os.path.join(HERE, "results")), "m73")


def load(name):
    path = os.path.join(OUT, name)
    return json.load(open(path, encoding="utf-8")) if os.path.isfile(path) else None


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def main():
    summary, ref, tol, cost = load("SUMMARY.json"), load("reference.json"), load("tolerance.json"), load("cost.json")
    rows = summary["scenarios"]
    lines = ["# M7.3: S8, locating planted defects", "",
             "Generated by `testbed/m73_summarize.py` from the files in this folder (written by "
             "`testbed/m73_locate.py` and `testbed/m73_tolerance.py`). RTX 4070 Ti (12 GB), WSL2, "
             f"torch {ref['torch'] if ref else '?'}, transformers {ref['transformers'] if ref else '?'}, bfloat16. "
             "Each scenario ran in a process of its own with entail on; it located the fault with `entail.locate()` in "
             "that process, and `entail locate` located it again from the record files the process left in "
             "`logs/<scenario>/`. \"Output wrong\": the greedy tokens differ from the reference run's (entail not "
             "installed) for what the run was meant to compute, or the run failed.", "",
             f"**Located: {summary['located']} of {summary['of']}** (both ways agreeing with where the defect was "
             f"planted).", "",
             "| scenario | planted | entail | output wrong | in process | from records | first line |",
             "|---|---|---|---|---|---|---|"]
    details = []
    for name, r in rows.items():
        if name in ("reference", "cost"):
            continue
        mine = load(f"{name}.json") or {}
        planted = mine.get("planted") or {"rope_observe": "rope_scaling restated after the config was built",
                                          "rope_debug": "rope_scaling restated after the config was built",
                                          "kv_seeded": "a restore drops the last KV token of every layer at step 2",
                                          "code_rb01": "rolebench 01: a reordered buffer read as the original layout",
                                          "code_rb04": "rolebench 04: a replicated value reduced again",
                                          "healthy": "nothing"}.get(name, "")
        first = (mine.get("lines") or [""])[0].replace("[entail] where: ", "")
        lines.append(f"| {name} | {cell(planted)} | {r['mode']}, {r['policy']} | {r['output_wrong']} | "
                     f"{'yes' if r['located_in_process'] else 'NO'} | {'yes' if r['located_from_records'] else 'NO'} | "
                     f"{cell(first)} |")
        details += [f"### {name}", "", f"- expected: {json.dumps(r['expect'])}"]
        if mine.get("failed"):
            details.append(f"- the run failed: `{cell(mine['failed'][:300])}`")
        if mine.get("stopped"):
            details.append(f"- entail stopped the run (debug mode refuses what breaks): "
                           f"`{cell(mine['stopped'].splitlines()[0][:300])}`")
        if mine.get("text"):
            details.append(f"- output: {cell(repr(mine['text'][:160]))}")
        details.append("- in this process:")
        details += [f"  - `{cell(x)}`" for x in mine.get("lines", [])]
        there = r.get("from_records") or {}
        details.append(f"- from the records ({', '.join(r.get('records', []))}): broken_at `{there.get('broken_at')}`, "
                       f"suspects {json.dumps(there.get('suspects'))}")
        details.append("")
    lines += ["", "Notes", "",
              "- `rope_observe`: transformers 5.17 drops `rope_theta` when `rope_scaling` is restated after the config "
              "is built, and then cannot build Qwen3's yarn rotary embedding (its base is None): the defect is loud "
              "in transformers (vLLM falls back to 10000 silently, M3.5). The silent load-boundary case is "
              "`config_typo`.",
              "- `unchecked`: gemma-2-2b-it kept its 32 greedy tokens with the planted attention's scale 15% off "
              "(832 calls, every layer at every step; `unchecked_scale_x1.15.json`); the scale is doubled here.", ""]
    if tol:
        lines += ["## Tolerance of the layer comparison (bfloat16)", "",
                  "`tolerance.json`: largest |layer - reference| / largest |reference| per call, float32 references. "
                  "Healthy: one prompt and 8 decode steps (8 forward passes), every call.", "",
                  "| model | layer | calls | first call | every layer once (prompt pass) | every call |",
                  "|---|---|---|---|---|---|"]
        for fam, layers in tol["healthy"].items():
            for layer, s in layers.items():
                lines.append(f"| {fam} | {layer} | {s['calls']} | {s['first']:.4f} | {s['prompt_pass_max']:.4f} | "
                             f"{s['max']:.4f} |")
        lines += ["", "Planted on Qwen3-4B (the layer where it was planted):", "",
                  "| fault | first call | every layer once | every call | output changed |", "|---|---|---|---|---|"]
        for name, v in tol["planted"].items():
            s = v.get("attention") or v.get("mlp")
            lines.append(f"| {name} | {s['first']:.4f} | {s['prompt_pass_max']:.4f} | {s['max']:.4f} | "
                         f"{v['output_changed']} |")
        lines += ["", "- The tolerance 3e-2 sits above every healthy call (largest 0.0163) and below every planted "
                      "fault compared on every call; compared on every layer once it sees 5% and up, and on the first "
                      "call in all only 15% and up. The watch compares every layer once by default.", ""]
    if cost:
        lines += ["## Cost of the diagnosis site (S4: at most 2x)", "",
                  f"Qwen3-4B, {cost['new_tokens']} greedy tokens from \"{cost['prompt']}\", {cost['reps']} alternating "
                  "repetitions after a warm-up, medians. `debug`: every check (the KV container contract installed); "
                  "`debug_propagation`: and operation-level propagation; `diagnosis`: and attention, MLP and RMSNorm "
                  "compared with float32 references (every layer once per generate).", "",
                  "| attention | off (s) | debug | debug + propagation | diagnosis | same tokens as off |",
                  "|---|---|---|---|---|---|"]
        for impl in ("eager", "sdpa"):
            c = cost[impl]
            off = sorted(c["seconds"]["off"])[len(c["seconds"]["off"]) // 2]
            m = c["median_x_off"]
            same = all(c["same_tokens_as_off"].values())
            lines.append(f"| {impl} | {off} | {m['debug']}x | {m['debug_propagation']}x | {m['diagnosis']}x | "
                         f"{same} |")
        lines.append("")
    lines += ["## Details", ""] + details
    with open(os.path.join(OUT, "SUMMARY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.join(OUT, "SUMMARY.md"))


if __name__ == "__main__":
    main()
