"""M9.3: testbed/results/m93/SUMMARY.md - the three gaps M9.1 found, after their fixes, from the files m93_run.sh
wrote (and s1_s3.json from m91_s1.py over results/m93/engines). Only values read from those files are written.
Run: python testbed/m93_summarize.py
"""
import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
M93 = os.path.join(HERE, "results", "m93")
ROPE = os.path.join(os.path.dirname(HERE), "issue_track", "rope_override", "results")


def j(*parts):
    p = os.path.join(*parts)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def main():
    L = ["# M9.3: the gaps M9.1 found, fixed and measured again", "",
         "Generated by `testbed/m93_summarize.py` from the files `testbed/m93_run.sh` wrote (RTX 4070 Ti, WSL2).", ""]
    d = j(M93, "s1_s3.json")
    L += ["## Gap 1: the chat template where transformers and SGLang apply it", ""]
    if d:
        L += [f"S1 over the healthy runs (3 models x 3 engines, `m91_s1.py`, passes at request boundaries counted): "
              f"M3's yardstick {d['S1_m3_yardstick']['totals']}; every declared fact {d['S1_wider']['totals']}.", "",
              "| model | engine | fact | state | boundaries | consumed in the run |", "|---|---|---|---|---|---|"]
        for x in d["S1_wider"]["facts"]:
            if x["fact"] == "Template":
                L.append(f"| {x['model']} | {x['engine']} | {x['fact']} | {x['state']} | "
                         f"{', '.join(x['boundaries']) or '-'} | {x['consumed_in_run'] or 'not consumed'} |")
    L += ["", "SGLang's OpenAI server (`m93_sglang_serve.py`, Qwen3-4B, two chat requests each):", "",
          "| condition | responses | decisions not passing | counted |", "|---|---|---|---|"]
    for c in ("healthy", "file", "builtin", "strict"):
        r = j(M93, f"sglang_{c}.json")
        if not r:
            L.append(f"| {c} | missing | | |")
            continue
        resp = ", ".join(str(q.get("status")) for q in r.get("requests") or []) or "-"
        dec = "; ".join(sorted({f"{x['boundary']} {x['verdict']}" for x in r.get("decisions", [])})) or "none"
        cnt = "; ".join(f"{k.split(' ', 1)[1]}: checks {v.get('checks')}, broken {v.get('broken')}, "
                        f"refused {v.get('refused')}" for k, v in r.get("counted", {}).items() if v.get("checks"))
        L.append(f"| {c} | {resp} | {dec} | {cnt or '-'} |")
    w = j(M93, "rerun", "m54", "healthy_on.json")
    if w:
        b = {k.split(" ", 1)[1]: (s.get("checks"), s.get("broken")) for k, s in w.get("summaries", {}).items()
             if k.split(" ", 1)[1].startswith("request:")}
        L += ["", f"vLLM's OpenAI server (M5.4's healthy server again): request boundaries counted {b} - the tokenizer's "
                  f"own hook steps aside inside vLLM's renders (no request:transformers boundary)."]
    L += ["", "## Gap 2: RoPE keys outside the vocabulary", ""]
    if d:
        L += [f"- readers' problems per model: {d['S1_wider']['reader_problems']}"]
    lc = j(ROPE, "LC_m93.json")
    rec = os.path.join(M93, "engines", "fd_rope_on.record.jsonl")
    if lc and os.path.exists(rec):
        rope = sorted({(r["boundary"], r["verdict"]) for r in (json.loads(x) for x in open(rec, encoding="utf-8")
                                                               if x.strip())
                       if "verdict" in r and "rope" in r["boundary"]})
        L += [f"- fd-rope with entail on (vocabulary v4): GSM8K {sum(lc['gsm8k']['correct'])}/{lc['gsm8k']['n']}, "
              f"the RoPE the engine holds {lc.get('rope_parameters_in_engine')}, decisions {rope}"]
    L += ["", "## Gap 3: the transformers KV contract's cost (m51_transformers, 64 tokens, 8 pairs)", ""]
    t = j(M93, "rerun", "m51", "transformers.json")
    if t:
        L += ["| cache | on / off (medians) | pairwise median | control / off | same output |", "|---|---|---|---|---|"]
        for c in ("dynamic", "static"):
            s = t[c]["seconds"]
            pr = statistics.median(on / off for on, off in zip(s["load"], s["off"]))
            L.append(f"| {c} | {t[c]['multiplier']} | {pr:.3f} | {t[c]['control_multiplier']} | {t[c]['same_output']} |")
    if d:
        L += ["", "## S3 and S4 load, the healthy runs again", "",
              "Every broken, refused or resolved decision: " + "; ".join(
                  f"{a['model']} / {a['engine']}: {a['verdict']} at {a['boundary']}"
                  for a in d["S3"]["broken_refused_resolved"]) + ".",
              f"Load share: largest {max(r['entail_share_of_load'] for r in d['S4_load']):.4f}."]
    u = os.path.join(M93, "unit_tests.log")
    if os.path.exists(u):
        lines = open(u, encoding="utf-8").read().splitlines()
        passed = [x for x in lines if x.startswith("PASS")]
        failed = [x for x in lines if x.startswith("FAIL")]
        checks = sum(int(x.split("(")[-1].split()[0]) for x in passed)
        L += ["", f"Unit tests: {len(passed)} files pass ({checks} checks), {len(failed)} fail."]
    with open(os.path.join(M93, "SUMMARY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
