"""M15.7: summarise testbed/results/m15/sweep_static.json into SWEEP_SUMMARY.md (counts, findings, the models a
rule could not decide, RoPE keys still outside the vocabulary). Reads the result file only.
Run: python testbed/m15/sweep_summarize.py"""
import collections
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(os.path.dirname(HERE)), "testbed", "results", "m15")


def main():
    d = json.load(open(os.path.join(OUT, "sweep_static.json"), encoding="utf-8"))
    rows = d["rows"]
    verdicts = collections.Counter()
    by_rule = collections.Counter()
    loaders = collections.Counter()
    two_sources, rows_none, mistral, errors = [], [], [], []
    broken, unknown_notes = [], collections.Counter()
    rotary_left = collections.Counter()
    rotary_types = collections.Counter()
    nbytes = 0
    for r in rows:
        nbytes += r.get("bytes") or 0
        if r.get("error"):
            errors.append((r["id"], r["error"][:100]))
        for v in r.get("vocab", []):
            verdicts[v["verdict"]] += 1
            if v["verdict"] != "pass":
                by_rule[(v["verdict"], v["rule"][:60])] += 1
            if v["verdict"] == "broken":
                broken.append((r["id"], v["note"][:200], r.get("reproduce")))
            if v["verdict"] == "unknown":
                unknown_notes[v["note"][:70]] += 1
        s = r.get("sources") or {}
        cands = s.get("candidates") or []
        if len({c[0] for c in cands}) > 1:
            two_sources.append((r["id"], cands, s.get("rows"), [v["verdict"] for v in r.get("vocab", [])]))
        if (r.get("rows") or {}).get("n") is None:
            rows_none.append((r["id"], (r.get("rows") or {}).get("where")))
        if r.get("mistral_files"):
            mistral.append((r["id"], r["mistral_files"]))
        loaders[(r.get("tokenizer") or {}).get("class", "error")] += 1
        for p in (r.get("rotary") or {}).get("problems", []):
            key = p.split(":", 1)[-1].strip()[:90]
            rotary_left[key] += 1
        for f in (r.get("rotary") or {}).get("facts", []):
            t = f.split("rope_type='")[1].split("'")[0] if "rope_type='" in f else "?"
            rotary_types[t] += 1
    L = [f"# M15.7 정적 훑기 요약 ({d.get('when')}; 모델 {len(rows)}개; 내려받은 토크나이저 파일 {nbytes / 2**20:.0f} MB)", "",
         "Generated by `testbed/m15/sweep_summarize.py` from `sweep_static.json`. 정의: `broken` = 폴더가 선언한 것과 엔진(transformers AutoTokenizer)이 만든 것이 어긋남; 재현 칸은 같은 문장을 각 출처로 토큰화한 id.",
         "", "## Vocab 판정", "", "| 판정 | 수 |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in sorted(verdicts.items())]
    L += ["", "### 판정별 규칙 (pass 제외)", "", "| 판정 | 규칙 | 수 |", "|---|---|---|"]
    L += [f"| {k[0]} | {k[1]} | {v} |" for k, v in by_rule.most_common()]
    L += ["", "### `unknown`의 이유", "", "| 이유 | 수 |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in unknown_notes.most_common(12)]
    L += ["", "## 발견 후보 (`broken`)", ""]
    if broken:
        L += ["| 모델 | 판정문 | 재현(출처별 id) |", "|---|---|---|"]
        L += [f"| {i} | {n} | {json.dumps(rep, ensure_ascii=False)[:160] if rep else ''} |" for i, n, rep in broken]
    else:
        L += ["없음."]
    L += ["", f"## 폴더가 두 어휘를 든 모델 ({len(two_sources)})", "", "| 모델 | 출처 | 행 | 판정 |", "|---|---|---|---|"]
    L += [f"| {i} | {c} | {rw} | {v} |" for i, c, rw, v in two_sources]
    L += ["", f"## Mistral 토크나이저 파일이 있는 모델 ({len(mistral)}; vLLM auto·transformers Mistral 백엔드는 이 검사 밖)", ""]
    L += [f"- {i}: {f}" for i, f in mistral] or ["없음."]
    L += ["", f"## 임베딩 행을 헤더에서 못 읽은 모델 ({len(rows_none)}; config vocab_size가 대신 섬)", ""]
    L += [f"- {i}: {w}" for i, w in rows_none] or ["없음."]
    L += ["", "## 토크나이저 클래스", "", "| 클래스 | 수 |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in loaders.most_common()]
    L += ["", "## RoPE", "", f"종류: {dict(rotary_types)}", "", "### 어휘 밖 RoPE 키 (문제 문구별)", "", "| 문구 | 수 |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in rotary_left.most_common(15)] or ["| 없음 | |"]
    L += ["", f"## 오류 ({len(errors)})", ""] + [f"- {i}: {e}" for i, e in errors]
    open(os.path.join(OUT, "SWEEP_SUMMARY.md"), "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L[:40]))


if __name__ == "__main__":
    main()
