"""Assemble results/*.json into RESULTS.md (markdown tables)."""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def fmt(x, nd=2):
    if x is None:
        return "-"
    if isinstance(x, (int, float)):
        return f"{x:.{nd}f}"
    return str(x)


def table(results):
    rows = ["| mode | batch | step ms (median) | min | max | first call ms | peak GiB | kernels/step | GPU busy ms | idle frac (UB) | status |",
            "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in results:
        k = r.get("kernels") or {}
        rows.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            r.get("mode"), r.get("batch"), fmt(r.get("step_ms_median")), fmt(r.get("step_ms_min")),
            fmt(r.get("step_ms_max")), fmt(r.get("first_call_ms"), 0), fmt(r.get("peak_mem_gib")),
            fmt(k.get("kernels_per_step"), 0), fmt(k.get("gpu_busy_ms_per_step")),
            fmt(k.get("idle_frac_upper_bound")), str(r.get("status", ""))[:70]))
    return "\n".join(rows)


def class_table(r):
    k = r.get("kernels") or {}
    bc = k.get("by_class") or {}
    if not bc:
        return "(no kernel data)"
    rows = ["| class | kernels/step | ms/step |", "|---|---|---|"]
    for c, v in bc.items():
        rows.append(f"| {c} | {v['count']:.0f} | {v['ms']:.2f} |")
    return "\n".join(rows)


def top_table(r, n=10):
    k = r.get("kernels") or {}
    top = (k.get("top") or [])[:n]
    if not top:
        return "(no kernel data)"
    rows = ["| kernel | class | count/step | ms/step |", "|---|---|---|---|"]
    for t in top:
        rows.append(f"| `{t['name'][:70]}` | {t['cls']} | {t['count']:.0f} | {t['ms']:.2f} |")
    return "\n".join(rows)


def main():
    out = ["# Phase 0 results (auto-generated by make_report.py)", ""]
    for path in sorted(glob.glob(os.path.join(HERE, "results", "*.json"))):
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        name = os.path.basename(path).replace(".json", "")
        env = d.get("env", {})
        out.append(f"## {name}")
        out.append("")
        out.append(f"- env: torch {env.get('torch')} / cuda {env.get('cuda')} / triton {env.get('triton')} / "
                   f"{env.get('device')} cc {env.get('cc')}")
        extra = f"; int4: {d.get('int4')}" if "int4" in d else ""
        out.append(f"- model source: {d.get('model_source')}; params: {d.get('params', 0)/1e9:.2f}B{extra}")
        out.append("")
        out.append(table(d["results"]))
        out.append("")
        for r in d["results"]:
            if r.get("status") != "ok" or not (r.get("kernels") or {}).get("by_class"):
                continue
            out.append(f"### {r['label']} : kernel classes")
            out.append("")
            out.append(class_table(r))
            out.append("")
            out.append("Top kernels:")
            out.append("")
            out.append(top_table(r))
            out.append("")
    with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote", os.path.join(HERE, "RESULTS.md"))


if __name__ == "__main__":
    main()
